name: Close inactive issue and PR
on:
  schedule:
    - cron: "30 1 * * *"

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v5
        with:
          days-before-issue-stale: 60
          days-before-issue-close: 3
          close-issue-message: "This issue was closed because it has been inactive."
          close-pr-message: "This PR was closed because it has been inactive."
          days-before-pr-stale: 60
          days-before-pr-close: 3
          repo-token: ${{ secrets.GITHUB_TOKEN }}
